# Generated by Django 4.1.7 on 2023-05-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceid', models.CharField(max_length=50)),
                ('sourcenamename', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=500)),
                ('urltoimage', models.CharField(max_length=500)),
                ('publishedAt', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
    ]
