# Generated by Django 4.1.7 on 2023-05-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('newssources', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sources',
            new_name='Source',
        ),
    ]
