# Generated by Django 4.1.7 on 2023-05-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newssources', '0002_rename_sources_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='sourcenamename',
            new_name='sourcename',
        ),
    ]
