# Generated by Django 4.1.7 on 2023-05-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newssources', '0003_rename_sourcenamename_source_sourcename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='publishedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='sourceid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='sourcename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='urltoimage',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
