# Generated by Django 4.1.7 on 2023-05-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newssources', '0005_source_useful'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='useful',
            new_name='use_in_ai',
        ),
    ]
