# Generated by Django 4.1.6 on 2023-05-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newssources', '0006_rename_useful_source_use_in_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='author',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='sourceid',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='sourcename',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
