# Generated by Django 4.1.7 on 2023-05-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newssources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.ManyToManyField(to='newssources.sources')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateTimeField()),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('comparison', models.TextField()),
                ('sources', models.ManyToManyField(to='newssources.sources')),
            ],
        ),
    ]
