# Generated by Django 4.1.6 on 2023-05-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imageurl',
            field=models.URLField(default='https://www.leukerecepten.nl/wp-content/uploads/2020/05/burrito.jpg'),
            preserve_default=False,
        ),
    ]
