# Generated by Django 4.1.7 on 2023-05-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_by_ai',
            field=models.BooleanField(default=False),
        ),
    ]
