# Generated by Django 4.1.6 on 2023-05-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comparison',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='article',
            name='imageurl',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(max_length=500),
        ),
    ]
