# Generated by Django 4.1.6 on 2023-05-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='long_content',
            field=models.TextField(blank=True, max_length=50000),
        ),
    ]
